module.exports = {
  theme: {
    darkSelector: '.dark',
    container: (theme) => ({
      center: true,
      padding: {
        default: theme('spacing.4'),
        sm: theme('spacing.6'),
        md: theme('spacing.24'),
        lg: theme('spacing.32'),
        xl: theme('spacing.40'),
      },
    }),
    fontSize: {
      '2xs': '0.625rem',
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
      jumbo: '6rem',
    },
    extend: {
      fontFamily: {
        sans: [
          'Inter',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
        mono: [
          // 'IBM Plex Mono',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
      },
      colors: {
        primary: {
          100: '#FBEEEE',
          200: '#F6D5D4',
          300: '#F0BBBA',
          400: '#E58886',
          500: '#DA5552',
          600: '#C44D4A',
          700: '#833331',
          800: '#622625',
          900: '#411A19',
        },
        gray: {
          100: '#F0EEF0',
          200: '#E0DFE0',
          300: '#C1BFC1',
          400: '#A2A0A3',
          500: '#838084',
          600: '#474448',
          700: '#3E3A3E',
          800: '#343134',
          900: '#211D20',
        },
        green: {
          100: '#E8F7EC',
          200: '#C5EBCE',
          300: '#A2DFB1',
          400: '#5CC677',
          500: '#16AE3C',
          600: '#149D36',
          700: '#0D6824',
          800: '#0A4E1B',
          900: '#073412',
        },
        moon: '#F3CA40',
        sun: '#F2A541',
      },
      maxWidth: {
        '8xl': '88rem',
        '7xl': '80rem',
        '2xs': '16rem',
      },
      maxHeight: {
        xs: '20rem',
        '2xs': '16rem',
        '3xs': '12rem',
        '4xs': '8rem',
        '5xs': '6rem',
        '6xs': '4rem',
        '7xs': '3rem',
        '8xs': '2rem',
      },
      opacity: {
        '90': '0.9',
      },
    },
  },
  variants: {
    backgroundColor: [
      'dark',
      'dark-hover',
      'dark-group-hover',
      'dark-even',
      'dark-odd',
    ],
    borderColor: ['dark', 'dark-focus', 'dark-focus-within', 'hover'],
    boxShadow: ['responsive', 'hover', 'focus', 'active', 'group-focus'],
    margin: ['responsive', 'last', 'first'],
    textColor: ['dark', 'dark-hover', 'dark-active', 'dark-placeholder'],
  },
  plugins: [
    require('@tailwindcss/ui'),
    require('tailwindcss-dark-mode')(),
    require('tailwindcss-modularscale')({
      sizes: [
        { size: 'xs', value: -2 },
        { size: 'sm', value: -1 },
        { size: 'base', value: 0 },
        { size: 'lg', value: 1 },
        { size: 'xl', value: 2 },
        { size: '2xl', value: 3 },
        { size: '3xl', value: 4 },
        { size: '4xl', value: 5 },
      ],
      base: 1.1,
      ratio: 1.2,
      unit: 'rem',
    }),
  ],
}
