import AboutContent from './about.mdx'

export const metadata = {
  title: 'About',
  // description: 'Generated by create next app',
}

export default function AboutPage() {
  return (
    <article className="post mx-auto">
      <h1>About</h1>
      <AboutContent />
    </article>
  )
}
