import Header from './components/header'
import Footer from './components/footer'
import '@/styles/globals.css'

// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ilja Panić',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        <Header />
        <main className="container mt-8">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
